name: PC-Haskell
version: '0.1.0.0'
synopsis: Programación competitiva con Haskell.
description: |
  Ejercicios para la preparación de las competiciones de programaciṕn usando
  Haskell. 
  
category: Education, Learning Haskell, Teaching
author: José A. Alonso
maintainer: JoseA.Alonso@gmail.com
copyright: José A. Alonso (2017)
license: GPL-3
github: jaalonso/PC-Haskell
extra-source-files:
- README.org
ghc-options: -Wall -fno-warn-type-defaults
library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
tests:
  doctest:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Glob
    - doctest
    - base
    - PC-Haskell
